### ISSUE TITLE
VNAV

### ISSUE THREAD

**Issue by Benjozork** [flybywiresim/aircraft#5966]
### Aircraft Version

Experimental

### Description

* [ ] Theoretical Approach Profile / DECEL path
  * [x] faf to 1000ft @ Vapp [^1]
    * [ ] Not always true... ex.: early stabilized approach (Vapp @ fdp) 
  * [ ] Deceleration from DES speed to Vapp
    * [x] First version with fixed fpa (-3deg) when possible
      * [x] Constant slope segments [^2]
        * [x] Naive linear computation
        * [x] Computation of deceleration in config changes
        * [x] Iterative solve to achieve minimal final altitude error at end of segment
    * [ ] CDA vs. Non-CDA modes
    * [ ] Take into account fpa/alt/spd constraints
      * [ ] Define what "fpa constraints" are
      * [ ] Constant speed segments [^2]
  * [ ] Theoretical Descent Profile
    * [x] Naive (rule of three) estimate to ToD 
    * [ ] Geometric path behind TAP / DECEL path
    * [ ] Idle path
      * [ ] Solve ToD iteratively to achieve minimal error to DECEL point
    * [ ] Repres. segment
  * [ ] Climb profile
    *  TBD
  * [ ] Emit pseudo-waypoints (ToD, DECEL) to MCDU and EFIS
    * [x] PwpCdaFfap1White
    * [x] PwpCdaFfap2White
    * [x] TopOfDescent
    * [ ] MCDU display
      * [x] Insertion
      * [ ] Statistics 
    * [x] EFIS display

[^1]: FBW-22-02
[^2]: FBW-22-03

### Discord Username (optional)

someperson#4953

**Comment by 2hwk** [comment]
Pre-empting the noise that will be created as a result of this issue, this will be locked for contributors only so that we can use this for its intended purpose of tracking.

**Comment by Benjozork** [comment]
Ok calculating flap 1 and 2 CDA pseudo wpts right now (in-non CDA mode, but this is useful for debugging), and they are too far out at some elevated airfields.

It looks like with higher T/D ratios we are reaching low deceleration rates (observed: -0.11kn/s) causing very long config change CONSTANT_SLOPE segments.

**Comment by Benjozork** [comment]
> * I really need to add iterative step prediction
> * I need to revert to LEVEL_DECELERATION or CONSTANT_DECELERATION below a certain deceleration rate

Done

**Comment by BlueberryKing** [comment]
We have basic VNAV now. If we want a tracking issue for the remaining tasks, we should make a new one as this one is stale.
