### ISSUE TITLE
[A380X] Wrong textures and push buttons in the cockpit

### ISSUE THREAD

**Issue by alepouna** [flybywiresim/aircraft#9386]
_based on #1410_

References can be found on the bottom of the page.

---
## Center Overhead
Bottom -> Top

### EXT LT
- [ ] #8828

### SIGNS
- [ ] **EMER EXIT LT** - OFF display is more red than amber when OFF
- [ ] **EMER EXIT LT** - Display does not have the dual 'dots' on the upper side [1]

### CABIN PRESS
- [ ] **CABIN ALT** section - Mode switch does not have the dual 'dots' on the upper side [1]
- [ ] **CABIN V/S** section - Mode switch does not have the dual 'dots' on the upper side [1]

### ELEC
- [ ] **Top row** - _ELMU_ has dual 'dots' when it shouldn't [1]

### MAINTENANCE 
- [ ] **ALL SECTION** - Section is backlight when it shouldn't be [1]
- [ ] **FUEL** section - _REFUEL_ has dual 'dots' when it shouldn't [1]
- [ ] **FUEL** section - _AUTO GND XFR_ has dual 'dots' when it shouldn't [1]
- [ ] **Second row** - _GND HF DATALINK_ has "OFF" label when it should be "OVRD" [1]
- [ ] **NSS** section - _GATELINK_ has "ON" label when it should be "OFF" [1]
- [ ] **AIR** section - _OVHT COND FANS RESET_ has a label when it should only have dual 'dots' on the bottom of the pb [1]
- [ ] **AIR** section - _AVNCS GND COOLG_ has label "ON" when it should be "OFF" [1]

---
## Left Overhead 
Bottom -> Top

## OXYGEN
- [ ] _PAX_ display has label "ON" on the bottom when it should dual 'dots' [1]

## EVAC
- [ ] _COMMAND_ pb display "EVAC" might be too red

## ELT
- [ ] _ON_ lt is missing a yellow-ish LED [1]
- [ ] _COVERGUARD_ is black when it should be red [1]
- [ ] _PANEL BACKLIGHT_ is yellow when it should be white [1]

---
## Right Overhead
Bottom -> Top

### DRAIMS
- [ ] **RAD NAV** - _Cover Guard_ seems to be completely transparent and not cover the actual button (passthrough) [1]
- [ ] **LEFT SELECTOR KEYS** - _1st line key (VHF1)_ has no texture [1]
- [ ] **LEFT SELECTOR KEYS** - _2nd line key (VHF1)_ has no texture [1]

### CKPT DOOR CTLR
Above the CB resets
- [ ] **PANEL** - Missing text "CKPT DOOR CTLR" [1]

### READING LIGHT
Top right of overhead
- [ ] **KNOB** - Missing label "READING LT" and missing OFF/BRT text & line

---
# References
1. https://ccntservice.airbus.com/apps/cockpits/a380/
